"""
Multi-Agent Handler for Curio News
Integrates Bedrock Agent Orchestrator with Lambda
"""
import json
import os
import boto3
from datetime import datetime
from bedrock_orchestrator import BedrockAgentOrchestrator

def handle_multi_agent_request(event, context):
    """
    Handle requests using the multi-agent orchestrator
    Returns real orchestration trace data
    """
    try:
        # Initialize orchestrator
        orchestrator = BedrockAgentOrchestrator()
        
        # Get user preferences from request
        body = {}
        if event.get('body'):
            try:
                body = json.loads(event['body'])
            except:
                pass
        
        location = body.get('location', 'San Francisco, CA')
        interests = body.get('interests', ['technology', 'social impact', 'culture'])
        
        # Run the multi-agent pipeline
        print(f"Starting multi-agent orchestration for location: {location}")
        result = orchestrator.orchestrate_news_generation(
            location=location,
            interests=interests
        )
        
        # Return response with orchestration trace
        return {
            'statusCode': 200,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Content-Type',
                'Access-Control-Allow-Methods': 'GET,POST,OPTIONS'
            },
            'body': json.dumps({
                'success': True,
                'news_items': result.get('curated_stories', []),
                'script': result.get('script', ''),
                'word_timings': result.get('word_timings', []),
                'audioUrl': result.get('audio_url', ''),
                'sources': result.get('sources', []),
                'generatedAt': datetime.utcnow().isoformat(),
                'traceId': result.get('trace_id', ''),
                'orchestration_trace': result.get('orchestration_trace', []),
                'agentOutputs': {
                    'favoriteStory': result.get('favorite_story'),
                    'weekendRecommendations': result.get('weekend_recommendations'),
                    'mediaEnhancements': result.get('media_enhancements')
                },
                'agentStatus': 'Multi-agent orchestration complete',
                'why': f'Generated by {len(result.get("orchestration_trace", []))} specialized Bedrock agents!'
            })
        }
        
    except Exception as e:
        print(f"Error in multi-agent handler: {str(e)}")
        import traceback
        traceback.print_exc()
        
        return {
            'statusCode': 500,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*'
            },
            'body': json.dumps({
                'success': False,
                'error': str(e),
                'message': 'Multi-agent orchestration failed'
            })
        }
