# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "myownnews"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "myownnews-mvp"
s3_prefix = "myownnews-mvp"
region = "us-west-2"
profile = "default"
parameter_overrides = "ModelId=\"anthropic.claude-3-haiku-20240307-v1:0\" NewsCategories=\"general,technology,business,science\" VoiceId=\"Joanna\" VoiceProvider=\"elevenlabs\" ElevenLabsApiKey=\"sk_1b52f159ca3da812f8bdef268f71ace8d6df11d9500debd3\" MaxArticles=\"10\""
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
