AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MyOwnNews MVP — RSS -> LLM script -> Polly MP3 -> S3

Parameters:
  ModelId:
    Type: String
    Default: anthropic.claude-3-haiku-20240307-v1:0
    Description: Claude 3 Haiku - Now available in us-west-2!
  NewsApiKey:
    Type: String
    Default: ""
    Description: News API key for fetching headlines
    NoEcho: true
  NewsCategories:
    Type: String
    Default: "general,technology,business,science"
    Description: Comma-separated News API categories (general, business, entertainment, health, science, sports, technology)
  VoiceId:
    Type: String
    Default: Joanna
    Description: Voice ID - Polly Neural (Joanna, Matthew, Amy, Emma) or ElevenLabs voice ID
  VoiceProvider:
    Type: String
    Default: polly
    Description: Voice provider - 'polly' for Amazon Polly or 'elevenlabs' for ElevenLabs
  ElevenLabsApiKey:
    Type: String
    Default: ""
    Description: ElevenLabs API key (optional, leave empty to use Polly)
    NoEcho: true
  NewsDataApiKey:
    Type: String
    Default: ""
    Description: NewsData.io API key (optional, for additional news sources)
    NoEcho: true
  MaxArticles:
    Type: Number
    Default: 3
    Description: How many items to summarize per run

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    MemorySize: 1024
    Tracing: Active

Resources:
  # DynamoDB table for caching and locks
  CurioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-curio-cache"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  # API Gateway for serving presigned URLs
  NewsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false



  NewsToAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: myownnews/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET: !Ref AssetsBucket
          MODEL_ID: !Ref ModelId
          NEWS_API_KEY: !Ref NewsApiKey
          NEWSDATA_API_KEY: !Ref NewsDataApiKey
          NEWS_CATEGORIES: !Ref NewsCategories
          VOICE_ID: !Ref VoiceId
          VOICE_PROVIDER: !Ref VoiceProvider
          ELEVENLABS_API_KEY: !Ref ElevenLabsApiKey
          MAX_ARTICLES: !Ref MaxArticles
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AssetsBucket
        - Statement:
            - Sid: AllowBedrockInvoke
              Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
            - Sid: AllowPolly
              Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: "*"

      Events:
        # Optional schedule, enable later after testing
        # DailySchedule:
        #   Type: Schedule
        #   Properties:
        #     Schedule: cron(0 13 * * ? *)
        #     Name: MyOwnNewsDaily
        #     Enabled: false

  # API: bootstrap endpoint for smart caching
  BootstrapFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: handlers.bootstrap
      Environment:
        Variables:
          BUCKET: !Ref AssetsBucket
          CURIO_TABLE: !Ref CurioTable
          CORS_ALLOW_ORIGIN: "*"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CurioTable
        - S3ReadPolicy:
            BucketName: !Ref AssetsBucket
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /bootstrap
            Method: GET

  # API: list latest audio/scripts with presigned URLs
  ListLatestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: handlers.list_latest
      Environment:
        Variables:
          BUCKET: !Ref AssetsBucket
          CORS_ALLOW_ORIGIN: "*"
          PRESIGN_EXPIRES: 1200  # 20 minutes
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AssetsBucket
      Events:
        ApiLatest:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /latest
            Method: GET

  # API: sign a given key (optional helper)
  SignKeyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: handlers.sign_key
      Environment:
        Variables:
          BUCKET: !Ref AssetsBucket
          CORS_ALLOW_ORIGIN: "*"
          PRESIGN_EXPIRES: 600
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AssetsBucket
      Events:
        ApiSign:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /sign
            Method: GET

Outputs:
  BucketName:
    Value: !Ref AssetsBucket
  FunctionName:
    Value: !Ref NewsToAudioFunction
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${NewsApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  LatestEndpoint:
    Description: Latest news endpoint
    Value: !Sub "https://${NewsApi}.execute-api.${AWS::Region}.amazonaws.com/prod/latest"
