AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MyOwnNews MVP — RSS -> LLM script -> Polly MP3 -> S3

Parameters:
  ModelId:
    Type: String
    Default: anthropic.claude-3-haiku-20240307-v1:0
    Description: Claude 3 Haiku - Now available in us-west-2!
  NewsApiKey:
    Type: String
    Default: "56e5f744fdb04e1e8e45a450851e442d"
    Description: News API key for fetching headlines (optional - RSS feeds work without it)
    NoEcho: false
  NewsCategories:
    Type: String
    Default: "general,technology,business,science"
    Description: News categories for content curation
  VoiceId:
    Type: String
    Default: Matthew
    Description: Amazon Polly voice ID (Joanna, Matthew, Amy, Emma, etc.)
  VoiceProvider:
    Type: String
    Default: polly
    Description: Voice provider - currently using Amazon Polly
  MaxArticles:
    Type: Number
    Default: 8
    Description: Maximum articles to process per generation
  CloudWatchMetricsNamespace:
    Type: String
    Default: "CurioNews/BedrockAgents"
    Description: CloudWatch custom metrics namespace for Bedrock agent tracking

Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    MemorySize: 1024
    Tracing: Active

Resources:
  # DynamoDB table for caching and locks
  CurioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # API Gateway for serving presigned URLs
  NewsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With,Accept,Origin'"
        AllowOrigin: "'*'"
        MaxAge: "'86400'"
        AllowCredentials: false
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With,Accept,Origin'"
              Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Requested-With,Accept,Origin'"
              Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"

  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, HEAD]
            AllowedOrigins: ['*']
            ExposedHeaders: ['ETag', 'Content-Length', 'Content-Type']
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldAudioFiles
            Status: Enabled
            ExpirationInDays: 7
            Prefix: audio/
          - Id: DeleteOldScripts
            Status: Enabled
            ExpirationInDays: 30
            Prefix: scripts/
          - Id: DeleteRateLimitFiles
            Status: Enabled
            ExpirationInDays: 1
            Prefix: rate-limit/





  NewsToAudioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: myownnews/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET: !Ref AssetsBucket
          MODEL_ID: !Ref ModelId
          NEWS_API_KEY: !Ref NewsApiKey
          NEWS_CATEGORIES: !Ref NewsCategories
          VOICE_ID: !Ref VoiceId
          VOICE_PROVIDER: !Ref VoiceProvider
          MAX_ARTICLES: !Ref MaxArticles
          CURIO_TABLE: !Ref CurioTable
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AssetsBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref CurioTable
        - Statement:
            - Sid: AllowBedrockInvoke
              Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
            - Sid: AllowPolly
              Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: "*"

      Events:
        # API endpoint for manual news generation
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /generate-news
            Method: POST
        # Daily schedule for fresh news generation
        MorningSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 13 * * ? *)  # 1 PM UTC = 9 AM EST / 8 AM EST (depending on DST)
            Name: MyOwnNewsMorning
            Enabled: true
        EveningSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 23 * * ? *)  # 11 PM UTC = 7 PM EST / 6 PM EST (depending on DST)
            Name: MyOwnNewsEvening
            Enabled: true

  # API: CONSOLIDATED MAIN FUNCTION - handles all API endpoints
  CurioNewsMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: main_handler.lambda_handler
      Timeout: 180
      MemorySize: 1024
      Environment:
        Variables:
          BUCKET: !Ref AssetsBucket
          CURIO_TABLE: !Ref CurioTable
          CORS_ALLOW_ORIGIN: "*"
          NEWS_API_KEY: !Ref NewsApiKey
          MODEL_ID: !Ref ModelId
          VOICE_ID: !Ref VoiceId
          NEWS_CATEGORIES: !Ref NewsCategories
          VOICE_PROVIDER: !Ref VoiceProvider
          MAX_ARTICLES: !Ref MaxArticles
          PRESIGN_EXPIRES: 600
          # Enable Bedrock Multi-Agent Orchestration
          USE_BEDROCK_AGENTS: "false"
          ENABLE_MULTI_AGENT: "true"
          # Bedrock Agent IDs - loaded from Parameter Store at runtime
          # These are fallback values; the orchestrator will load from SSM if not set
          BEDROCK_AGENT_CONTENT_CURATOR_ID: ""
          BEDROCK_AGENT_SOCIAL_IMPACT_ANALYZER_ID: ""
          BEDROCK_AGENT_STORY_SELECTOR_ID: ""
          BEDROCK_AGENT_SCRIPT_WRITER_ID: ""
          BEDROCK_AGENT_ENTERTAINMENT_CURATOR_ID: ""
          BEDROCK_AGENT_MEDIA_ENHANCER_ID: ""
          # CloudWatch Metrics Configuration
          CLOUDWATCH_METRICS_NAMESPACE: !Ref CloudWatchMetricsNamespace
          ENABLE_AGENT_METRICS: "true"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CurioTable
        - S3CrudPolicy:
            BucketName: !Ref AssetsBucket
        - Statement:
            - Sid: AllowBedrockInvoke
              Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
            - Sid: AllowBedrockAgents
              Effect: Allow
              Action:
                - bedrock-agent-runtime:InvokeAgent
                - bedrock-agent:GetAgent
                - bedrock-agent:ListAgents
                - bedrock-agent:GetAgentAlias
                - bedrock-agent:ListAgentAliases
              Resource: "*"
            - Sid: AllowSSMParameterAccess
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Resource: 
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/curio-news/bedrock-agents/*"
            - Sid: AllowPolly
              Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: "*"
            - Sid: AllowCloudWatchMetrics
              Effect: Allow
              Action:
                - cloudwatch:GetMetricStatistics
                - cloudwatch:ListMetrics
                - cloudwatch:PutMetricAlarm
                - cloudwatch:PutMetricData
                - cloudwatch:DescribeAlarms
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:FilterLogEvents
              Resource: "*"
      Events:
        # Core API endpoints
        BootstrapApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /bootstrap
            Method: GET
        GenerateFreshApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /generate-fresh
            Method: POST
        LatestApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /latest
            Method: GET
        # Agent status endpoint
        AgentStatusApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /agent-status
            Method: GET
        # Monitoring endpoints
        MonitoringDashboardApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /monitoring/dashboard
            Method: GET
        MonitoringDebugApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /monitoring/debug/{run_id}
            Method: GET
        MonitoringMetricsApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /monitoring/metrics/{run_id}
            Method: GET
        MonitoringSetupApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /monitoring/setup
            Method: POST
        # Debugging endpoints
        DebuggingAnalysisApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /debugging/analysis
            Method: GET
        DebuggingRealtimeWithRunIdApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /debugging/realtime/{run_id}
            Method: GET
        DebuggingRealtimeApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /debugging/realtime
            Method: GET
        DebuggingTroubleshootingWithTypeApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /debugging/troubleshooting/{issue_type}
            Method: GET
        DebuggingTroubleshootingApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /debugging/troubleshooting
            Method: GET
        DebuggingVisualizationApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /debugging/visualization
            Method: GET
        # Utility endpoints
        SignApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /sign
            Method: GET
        TraceApi:
          Type: Api
          Properties:
            RestApiId: !Ref NewsApi
            Path: /trace/{traceId+}
            Method: GET



Outputs:
  BucketName:
    Value: !Ref AssetsBucket
  FunctionName:
    Value: !Ref NewsToAudioFunction
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${NewsApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  LatestEndpoint:
    Description: Latest news endpoint
    Value: !Sub "https://${NewsApi}.execute-api.${AWS::Region}.amazonaws.com/prod/latest"
