import React from "react";

export default function AudioPlayer() {
  const audioRef = React.useRef<HTMLAudioElement>(null);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [meta, setMeta] = React.useState<{sources:string[]; generatedAt:string; why:string; traceId?:string} | null>(null);

  const playLatest = async () => {
    try {
      setError(null);
      setLoading(true);
      
      // Use bootstrap endpoint for smart caching
      const r = await fetch(`${process.env.REACT_APP_API_URL}/bootstrap`, { method: "GET" });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const data = await r.json();
      
      const { audioUrl, sources, generatedAt, why, traceId, shouldRefresh, agentStatus } = data;

      setMeta({ sources, generatedAt, why, traceId });
      
      // Play audio immediately (cached content)
      if (audioRef.current && audioUrl) {
        audioRef.current.src = audioUrl;
        await audioRef.current.play();
      }
      
      // If fresh content is being generated, show progress
      if (shouldRefresh && data.generationStarted) {
        setMeta(prev => prev ? { ...prev, why: `🤖 ${agentStatus}: ${why}` } : null);
        
        // Start real agent generation
        try {
          const generateR = await fetch(`${process.env.REACT_APP_API_URL}/generate-fresh`, { method: "POST" });
          if (generateR.ok) {
            const generateData = await generateR.json();
            const runId = generateData.runId;
            
            // Poll for agent progress
            const pollInterval = setInterval(async () => {
              try {
                const statusR = await fetch(`${process.env.REACT_APP_API_URL}/agent-status?runId=${runId}`);
                if (statusR.ok) {
                  const statusData = await statusR.json();
                  const { currentAgent, status } = statusData;
                  
                  // Update UI with current agent
                  const agentEmojis: { [key: string]: string } = {
                    'NEWS_FETCHER': '📰',
                    'CONTENT_CURATOR': '🎯', 
                    'FAVORITE_SELECTOR': '⭐',
                    'SCRIPT_GENERATOR': '📝',
                    'MEDIA_ENHANCER': '🎨',
                    'WEEKEND_EVENTS': '🎉',
                    'COMPLETED': '✅'
                  };
                  
                  const emoji = agentEmojis[currentAgent] || '🤖';
                  setMeta(prev => prev ? { 
                    ...prev, 
                    why: `${emoji} ${currentAgent.replace('_', ' ')}: ${status}...` 
                  } : null);
                  
                  // Check if generation is complete
                  if (status === 'SUCCESS' || currentAgent === 'COMPLETED') {
                    // Get the fresh content
                    const freshR = await fetch(`${process.env.REACT_APP_API_URL}/latest`);
                    if (freshR.ok) {
                      const freshData = await freshR.json();
                      setMeta({ 
                        sources: freshData.sources, 
                        generatedAt: freshData.generatedAt, 
                        why: "✨ Fresh content generated by 6 specialized Bedrock Agents!", 
                        traceId: freshData.traceId 
                      });
                      
                      // Hot-swap audio
                      if (audioRef.current && freshData.audioUrl) {
                        audioRef.current.src = freshData.audioUrl;
                      }
                    }
                    clearInterval(pollInterval);
                  }
                }
              } catch (e) {
                console.log("Agent status polling error:", e);
              }
            }, 2000); // Poll every 2 seconds for agent progress
            
            // Clear polling after 2 minutes
            setTimeout(() => clearInterval(pollInterval), 120000);
          }
        } catch (e) {
          console.log("Generate fresh error:", e);
        }
      }
      
    } catch (e:any) {
      setError(e?.message || "Failed to fetch latest brief.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="curio-audio">
      <button onClick={playLatest} disabled={loading} aria-busy={loading}>
        {loading ? "Preparing brief…" : "▶ Play Today's 90-sec Brief"}
      </button>
      <audio ref={audioRef} controls preload="none" />
      {error && <p style={{color:"crimson"}}>Error: {error}</p>}
      {meta && (
        <div className="provenance">
          <p><strong>Generated:</strong> {new Date(meta.generatedAt).toLocaleString()}</p>
          <p><strong>Why it made the brief:</strong> {meta.why}</p>
          <p><strong>Sources:</strong> {meta.sources.join(" · ")}</p>
          {meta.traceId && <a href={`${process.env.REACT_APP_API_URL}/trace/${meta.traceId}`} target="_blank" rel="noreferrer">View agent trace</a>}
        </div>
      )}
    </div>
  );
}