import React from "react";

export default function AudioPlayer() {
  const audioRef = React.useRef<HTMLAudioElement>(null);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [meta, setMeta] = React.useState<{sources:string[]; generatedAt:string; why:string; traceId?:string} | null>(null);

  const playLatest = async () => {
    try {
      setError(null);
      setLoading(true);
      
      // Use bootstrap endpoint for smart caching
      const r = await fetch(`${process.env.REACT_APP_API_URL}/bootstrap`, { method: "GET" });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const data = await r.json();
      
      const { audioUrl, sources, generatedAt, why, traceId, shouldRefresh, agentStatus } = data;

      setMeta({ sources, generatedAt, why, traceId });
      
      // Play audio immediately (cached content)
      if (audioRef.current && audioUrl) {
        audioRef.current.src = audioUrl;
        await audioRef.current.play();
      }
      
      // If fresh content is being generated, show progress
      if (shouldRefresh && data.generationStarted) {
        setMeta(prev => prev ? { ...prev, why: `🤖 ${agentStatus}: ${why}` } : null);
        
        // Poll for fresh content every 5 seconds
        const pollInterval = setInterval(async () => {
          try {
            const freshR = await fetch(`${process.env.REACT_APP_API_URL}/latest`, { method: "GET" });
            if (freshR.ok) {
              const freshData = await freshR.json();
              if (freshData.generatedAt !== generatedAt) {
                // New content available!
                setMeta({ 
                  sources: freshData.sources, 
                  generatedAt: freshData.generatedAt, 
                  why: "✨ Fresh content generated by AI agents!", 
                  traceId: freshData.traceId 
                });
                
                // Hot-swap audio
                if (audioRef.current && freshData.audioUrl) {
                  audioRef.current.src = freshData.audioUrl;
                  // Don't auto-play the new content, let user choose
                }
                
                clearInterval(pollInterval);
              }
            }
          } catch (e) {
            console.log("Polling error:", e);
          }
        }, 5000);
        
        // Clear polling after 2 minutes
        setTimeout(() => clearInterval(pollInterval), 120000);
      }
      
    } catch (e:any) {
      setError(e?.message || "Failed to fetch latest brief.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="curio-audio">
      <button onClick={playLatest} disabled={loading} aria-busy={loading}>
        {loading ? "Preparing brief…" : "▶ Play Today's 90-sec Brief"}
      </button>
      <audio ref={audioRef} controls preload="none" />
      {error && <p style={{color:"crimson"}}>Error: {error}</p>}
      {meta && (
        <div className="provenance">
          <p><strong>Generated:</strong> {new Date(meta.generatedAt).toLocaleString()}</p>
          <p><strong>Why it made the brief:</strong> {meta.why}</p>
          <p><strong>Sources:</strong> {meta.sources.join(" · ")}</p>
          {meta.traceId && <a href={`${process.env.REACT_APP_API_URL}/trace/${meta.traceId}`} target="_blank" rel="noreferrer">View agent trace</a>}
        </div>
      )}
    </div>
  );
}