name: Deploy MyOwnNews

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy MyOwnNews
      uses: ./
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'
        stack-name: 'myownnews-${{ github.event.inputs.environment || 'dev' }}'
        news-api-key: ${{ secrets.NEWS_API_KEY }}
        elevenlabs-api-key: ${{ secrets.ELEVENLABS_API_KEY }}
        voice-provider: 'elevenlabs'
        voice-id: '21m00Tcm4TlvDq8ikWAM'
        
    - name: Output deployment info
      run: |
        echo "🎉 Deployment successful!"
        echo "📡 Function URL: ${{ steps.deploy.outputs.function-url }}"
        echo "🪣 S3 Bucket: ${{ steps.deploy.outputs.bucket-name }}"